name : create runner
on: workflow_dispatch

jobs:
  create-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: list files
        run: ls -al
